#!/usr/bin/env python3
"""Plot depth-stratified SAM segmentability heatmaps.

The default input is the latest clear-vs-fog depth comparison generated by
``coldfog_test/run_sam_depth_compare.py``. It draws two side-by-side heatmaps:

    (a) Matched IoU
    (b) Recall@0.5
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

TEXTWIDTH_IN = 5.768

SCRIPT_DIR = Path(__file__).resolve().parent
COLDFOG_TEST_DIR = SCRIPT_DIR.parent
DEFAULT_INPUT_CSV = (
    COLDFOG_TEST_DIR
    / "results/compare/latest_clear_vs_light_vs_medium_vs_heavy_depth/per_depth_bin.csv"
)

FOG_ORDER = ("light", "medium", "heavy")
FOG_LABELS = ("Light", "Medium", "Heavy")
DEPTH_ORDER = ("Near", "Middle", "Far")

METRICS = (
    ("matched_iou_vs_reference", "(a) Matched IoU"),
    ("mask_recall_at_0_5", "(b) Recall@0.5"),
)


def configure_matplotlib() -> None:
    plt.rcParams.update({
        "font.family": "Times New Roman",
        "font.size": 12,
        "axes.labelsize": 11,
        "axes.titlesize": 11,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 9,
        "figure.dpi": 300,
        "savefig.dpi": 300,
    })


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def metric_matrix(
    rows: list[dict[str, str]],
    metric_key: str,
) -> np.ndarray:
    lookup = {
        (row["query_tag"].strip().lower(), row["depth_bin"].strip()): row
        for row in rows
    }

    matrix = np.full((len(FOG_ORDER), len(DEPTH_ORDER)), np.nan, dtype=np.float64)
    missing: list[str] = []
    for row_index, fog in enumerate(FOG_ORDER):
        for col_index, depth_bin in enumerate(DEPTH_ORDER):
            row = lookup.get((fog, depth_bin))
            if row is None:
                missing.append(f"{fog}/{depth_bin}")
                continue
            value = row.get(metric_key, "")
            matrix[row_index, col_index] = float(value) if value else np.nan

    if missing:
        raise ValueError(
            "Missing required rows in per-depth-bin CSV: " + ", ".join(missing)
        )
    if np.isnan(matrix).any():
        raise ValueError(f"Metric {metric_key!r} contains empty or NaN values.")
    return matrix


def annotate_cells(ax: plt.Axes, matrix: np.ndarray) -> None:
    for row_index in range(matrix.shape[0]):
        for col_index in range(matrix.shape[1]):
            value = matrix[row_index, col_index]
            text_color = "white" if value < 0.45 else "black"
            ax.text(
                col_index,
                row_index,
                f"{value:.3f}",
                ha="center",
                va="center",
                color=text_color,
                fontsize=9,
            )


def style_heatmap_axes(ax: plt.Axes, subtitle: str) -> None:
    ax.set_xticks(np.arange(len(DEPTH_ORDER)), labels=DEPTH_ORDER)
    ax.set_yticks(np.arange(len(FOG_LABELS)), labels=FOG_LABELS)
    ax.tick_params(top=True, bottom=False, labeltop=True, labelbottom=False, length=0)
    ax.set_xlabel("Depth range", labelpad=8, fontsize=9)
    ax.xaxis.set_label_position("top")
    ax.set_ylabel("Fog level", fontsize=9)
    ax.text(
        0.5,
        -0.10,
        subtitle,
        transform=ax.transAxes,
        ha="center",
        va="top",
        fontsize=11,
    )

    ax.set_xticks(np.arange(len(DEPTH_ORDER) + 1) - 0.5, minor=True)
    ax.set_yticks(np.arange(len(FOG_LABELS) + 1) - 0.5, minor=True)
    ax.grid(which="minor", color="white", linewidth=1.2)
    ax.tick_params(which="minor", bottom=False, left=False)
    for spine in ax.spines.values():
        spine.set_visible(False)


def plot_heatmaps(
    rows: list[dict[str, str]],
    output_stem: Path,
    cmap_name: str,
) -> None:
    configure_matplotlib()

    matrices = [metric_matrix(rows, metric_key) for metric_key, _ in METRICS]
    fig, axes = plt.subplots(
        1,
        2,
        figsize=(TEXTWIDTH_IN, 2.75),
        gridspec_kw={"wspace": 0.55},
    )

    images = []
    for ax, matrix, (_, subtitle) in zip(axes, matrices, METRICS):
        image = ax.imshow(matrix, cmap=cmap_name, vmin=0.0, vmax=1.0, aspect="equal")
        images.append(image)
        annotate_cells(ax, matrix)
        style_heatmap_axes(ax, subtitle)

    fig.subplots_adjust(bottom=0.14)

    # cbar = fig.colorbar(
    #     images[-1],
    #     ax=axes,
    #     orientation="horizontal",
    #     fraction=0.06,
    #     pad=0.18,
    #     aspect=32,
    #     ticks=np.linspace(0, 1, 6),
    # )
    # cbar.set_label("Score")
    # cbar.ax.tick_params(labelsize=9)

    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_stem.with_suffix(".png"), bbox_inches="tight")
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Draw side-by-side heatmaps for depth-stratified SAM metrics."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=DEFAULT_INPUT_CSV,
        help=f"Path to per_depth_bin.csv (default: {DEFAULT_INPUT_CSV}).",
    )
    parser.add_argument(
        "--output-stem",
        type=Path,
        default=SCRIPT_DIR / "depth_stratified_sam_heatmaps",
        help="Output path without extension. A PNG file is written.",
    )
    parser.add_argument(
        "--cmap",
        default="cividis",
        help="Matplotlib sequential colormap name, e.g. cividis or viridis.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = load_rows(args.input_csv)
    if not rows:
        raise ValueError(f"No rows found in {args.input_csv}")
    plot_heatmaps(rows, args.output_stem, args.cmap)


if __name__ == "__main__":
    main()
